# Site settings
title: Julia Kraus' Data Science Portfolio
description: Julia Kraus' Data Science Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Julia Kraus
user_description: Professional data scientist, amateur classical guitar player and jazz dancer. Humanist. Studied M.Sc. in Mathematics, State examination as teacher of English, Latin and Mathematics. I love building things and believe in learning by teaching.
user_title: Data Scientist and Python Developer
email: j-kraus@gmx.de
twitter_username: none
github_username:  julia-kraus
linkedin_username:  julia-kraus

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
